### ISSUE TITLE
A screen shot would be nice

### ISSUE THREAD

**Issue by ndw** [cadadr/elisp#28]
If you could stick a graphic showing the Paper theme into the docs, that'd be nice.

**Comment by cadadr** [comment]
Thanks, I'll be able to add screenshots in a couple days.  Until then, they are available on the following page:

http://www.gkayaalp.com/emacs.html#paper

**Comment by cadadr** [comment]
Hi, I've added some screenshots to readme. Sorry for it taking  a bit more than a couple days...
