### ISSUE TITLE
Bibliothek

### ISSUE THREAD

**Issue by Arjay-El** [cadadr/elisp#30]
Loaded via Melpa. M-x bibliothek RTN gives this error (copied from Messages buffer):

pdf-info--normalize-file-or-buffer: Wrong type argument: stringp, bufferp, null, [cl-struct-package-desc pc-bufsw (20180107 1040) "PC style quick buffer switcher" nil single "melpa" nil ((:commit . "b99ba484e18ebf2b88654704146746490bb7625f") (:url . "https://github.com/ibukanov/pc-bufsw") (:keywords "buffer")) nil]

This is what is reported in the mini-buffer:
pdf-info-check-epdfinfo: pdf-info-epdfinfo-program is not executable

**Comment by cadadr** [comment]
The Melpa build of pdf-tools is troublesome, and that's what causes this
error.  ‘pdf-info-epdfinfo-program’ should point to the helper
executable but the Melpa build does not set that (or if I'm not mistaken
doesn't even compile the program).  I guess this should be reported to
Melpa itself.
