### ISSUE TITLE
library-el renamed to bibliothekel not been reflected on your website

### ISSUE THREAD

**Issue by declanqian** [cadadr/elisp#33]
See here. 
https://www.gkayaalp.com/emacs.html#library-el

And this link on your website is broken
https://melpa.org/#/library

Since you give the the link(https://www.gkayaalp.com/emacs.html) in your repo title, I guess it's ok for me open this issue here. Sorry for the noise.

**Comment by cadadr** [comment]
Hi, thanks for the report, not noise at all.  I'm working on a new website for this repository which I'll publish shortly.  The links in the elisp files and thus on Melpa will be updated just after that too.  So I'll close this and make a comment here to notify you when I publish.  Have a nice time!

**Comment by cadadr** [comment]
And that's done! See: <https://cadadr.github.io/elisp/index.html>.  Might require some polishing, but I'll make it better as time goes by. @declanqian
