### ISSUE TITLE
org-variable-pitch.el: support "org-list-allow-alphabetical"

### ISSUE THREAD

**Issue by GregorZattler** [cadadr/elisp#38]
With org-list-allow-alphabetical set to t, org recognizes ‘a.’, ‘A.’, ‘a)’ and ‘A)’ as beginning of a new list item. 

But org-variable-pitch.el does not support this by assigning the monospaced font in these cases.

It would be nice if it would.

Thanks for this useful minor mode, Gregor

**Comment by cadadr** [comment]
Hi @GregorZattler, thanks for your report, and you’re welcome!

I’ve just pushed commit 46ea37d on devel branch, can test the change and
report problems if you find any?  If you don’t find any problems I’ll
merge this into master so that it’ll appear on Melpa.

PS. TIL about ‘org-list-allow-alphabetical’, thanks for that!

-- 
İ. Göktuğ Kayaalp	<https://www.gkayaalp.com/>
			 024C 30DD 597D 142B 49AC
			 40EB 465C D949 B101 2427

**Comment by GregorZattler** [comment]
Hi Göktuğ,
* Göktuğ Kayaalp <notifications@github.com> [2019-01-24; 17:45]:
> I’ve just pushed commit 46ea37d on devel branch, can test the change and
> report problems if you find any?  If you don’t find any problems I’ll
> merge this into master so that it’ll appear on Melpa.
>
> PS. TIL about ‘org-list-allow-alphabetical’, thanks for that!

Thanks for your fast fix.  I produced a nested plain list with
all kinds of bullets, org-mode provides (via C-c -): Your patch
fixes the issue in all but one case.  It does not work for "*" as
the bullet sign.

Thanks again, Gregor

* Settings
#+begin_src emacs-lisp
  (org-mode)
  ; (setq org-variable-pitch-fixed-font "Overpass Mono")
  ; (setq variable-pitch "Overpass")
  (org-variable-pitch-minor-mode 1)
  (message "%s" org-list-allow-alphabetical)
#+end_src

#+RESULTS:
: t
* Plain list
1. Sed ut perspiciatis, unde omnis iste natus error sit
   voluptatem accusantium doloremque laudantium, totam rem
   aperiam eaque ipsa, quae ab illo inventore veritatis et quasi
   1) architecto beatae vitae dicta sunt, explicabo. Nemo enim
      ipsam voluptatem, quia voluptas sit, aspernatur aut odit
      aut fugit, sed quia consequuntur magni dolores eos, qui
      ratione
      a. voluptatem sequi nesciunt, neque porro quisquam est, qui
         dolorem ipsum, quia dolor sit amet consectetur
         adipisci[ng] velit, sed quia non-numquam [do] eius modi
         A. tempora inci[di]dunt, ut labore et dolore magnam
            aliquam quaerat voluptatem. Ut enim ad minima veniam,
            quis nostrum exercitationem ullam corporis suscipit
            a) Sed ut perspiciatis, unde omnis iste natus illo
               inventore veritatis et quasi architecto beatae
               vitae dicta sunt, explicabo. Nemo enim ipsam
               A) voluptatem, quia voluptas sit, aspernatur aut
                  odit aut fugit, sed quia consequuntur magni
                  dolores eos, qui ratione voluptatem sequi
                  - nesciunt, neque porro quisquam est, qui
                    dolorem ipsum, quia dolor sit amet
                    consectetur adipisci[ng] velit, sed quia
                    + non-numquam [do] eius modi tempora
                      inci[di]dunt, ut labore et dolore magnam
                      aliquam quaerat voluptatem. Ut enim ad
                      * minima veniam, quis nostrum
                        exercitationem ullam corporis suscipit
                        laboriosam, nisi ut aliquid ex ea
                        1. commodi consequatur? Quis autem vel
                           eum iure reprehenderit, qui in ea
                           voluptate velit esse, quam

**Comment by cadadr** [comment]
Hi Gregor!  I just pushed d982817 which accounts fo the ‘*’ lists.  I’m
closing the issue now, but feel free to report me if there are any
problems.  Otherwise, I’ll merge this into master tomorrow.
