### ISSUE TITLE
Make a public package archive for this repo

### ISSUE THREAD

**Issue by cadadr** [cadadr/elisp#41]
As an alternative method to install from this repo.

See `(info "(elisp) Package Archives")`

**Comment by cadadr** [comment]
Another option is to move some packages to the [Non-GNU ELPA](https://elpa.nongnu.org/) but I don't know enough about it yet.

Tired of MELPA's bullshit.

**Comment by hab25** [comment]
Hi, just passing by. Could you please expand on this?

> Tired of MELPA's bullshit.
