### ISSUE TITLE
forecast.el: Apple Acquires Dark Sky... API shutting down

### ISSUE THREAD

**Issue by gonewest818** [cadadr/elisp#47]
https://blog.darksky.net/dark-sky-has-a-new-home/

>iOS App
>
>There will be no changes to Dark Sky for iOS at this time. It will continue to be available for purchase in the App Store.
>
>Android and Wear OS App
>
>The app will no longer be available for download. Service to existing users and subscribers will continue until July 1, 2020, at which point the app will be shut down. Subscribers who are still active at that time will receive a refund.
>
>Website
>
>Weather forecasts, maps, and embeds will continue until July 1, 2020. The website will remain active beyond that time in support of API and iOS App customers.
>
>API
>
>Our API service for existing customers is not changing today, but we will no longer accept new signups. The API will continue to function through the end of 2021.
>
>As part of this transition, use of Dark Sky by Apple is subject to the Apple Privacy Policy, which can be found at apple.com/privacy.

**Comment by cadadr** [comment]
Thanks for the heads up! I would've missed that. Guess this'll require a rewrite. Will do that before the end of 2021, probably using https://openweathermap.org.  In the mean time, if you want to avoid Apple's privacy policy for some reason, you can use <https://github.com/aaronbieber/sunshine.el>.

I'll close this issue and make a new one referencing this for the rewrite.
