### ISSUE TITLE
org-variable-pitch.el: visual-line-mode line wraps cause extra indentation

### ISSUE THREAD

**Issue by yegortimoshenko** [cadadr/elisp#49]
Something about interaction between OVP and `visual-line-mode` is causing extra indentation on line wrap. For example, see:

![Screenshot from 2020-04-12 06-49-20](https://user-images.githubusercontent.com/1643293/79060141-15b90700-7c8a-11ea-9c64-5f63bca6ec07.png)

**Comment by yegortimoshenko** [comment]
Please disregard this ticket, it's an upstream Org mode issue (bzg/org-mode@bdf92cfcf7032bdd38585241227bd39c69fdc5a1 I think). After updating Org mode and setting `'(org-variable-pitch-fontify-headline-prefix t)` added in #46, it all renders perfectly.

**Comment by cadadr** [comment]
Hi, thanks for taking the time to report the issue and also to update when you figured out a solution for the problem!  Stay safe!
