### ISSUE TITLE
org-variable-pitch.el Drawers should be fixed pitch

### ISSUE THREAD

**Issue by psmith1303** [cadadr/elisp#55]
In OVP mode, drawers are in variable pitch, when they should be in fixed pitch (otherwise they don't line up correctly with the contents of the drawer.

The fix is to change the the function following function.

```
(defcustom org-variable-pitch-fixed-faces
  '(org-block
    org-block-begin-line
    org-block-end-line
    org-code
    org-document-info-keyword
    org-done
    org-formula
    org-indent
    org-meta-line
    org-special-keyword
    org-table
    org-todo
    org-verbatim
    org-date)
  "Faces to keep fixed-width when using ‘org-variable-pitch-minor-mode’."
  :group 'org-variable-pitch
  :type '(repeat symbol))
```

Insert `org-`drawer after `org-meta-line` -- that seems or work correctly.

**Comment by cadadr** [comment]
Thanks for the report! I added `org-drawer` to the list.

FWIW, where exactly you add the symbol isn't really important. If you want to add any faces to that list in your config, you can just use `add-to-list`, `cl-pushnew`, etc. to add the name of the face as a symbol.

**Comment by psmith1303** [comment]
Hi Göktuğ,

I'm something of a neophyte to Emacs/elisp/etc, so I'm not the most elegant at make suggestions/changes yet :)

Kind regards

Peter Smith
